// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace AllLive.Core.Danmaku.Proto
{


    [global::ProtoBuf.ProtoContract()]
    public partial class Response : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"messagesList")]
        public global::System.Collections.Generic.List<Message> messagesLists { get; set; } = new global::System.Collections.Generic.List<Message>();

        [global::ProtoBuf.ProtoMember(2, Name = @"cursor")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Cursor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public ulong? fetchInterval { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"now")]
        public ulong? Now { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string internalExt { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public uint? fetchType { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> routeParams { get; set; } = new global::System.Collections.Generic.Dictionary<string, string>();

        [global::ProtoBuf.ProtoMember(8)]
        public ulong? heartbeatDuration { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public bool? needAck { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string pushServer { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string liveCursor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12)]
        public bool? historyNoMore { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Message : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"method")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Method { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"payload")]
        public byte[] Payload { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long? msgId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int? msgType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"offset")]
        public long? Offset { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool? needWrdsStore { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public long? wrdsVersion { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string wrdsSubKey { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        //[global::ProtoBuf.ProtoMember(1, Name = @"common")]
        //public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

        //[global::ProtoBuf.ProtoMember(4)]
        //public bool? visibleToSender { get; set; }

        //[global::ProtoBuf.ProtoMember(5)]
        //public Image backgroundImage { get; set; }

        //[global::ProtoBuf.ProtoMember(6)]
        //[global::System.ComponentModel.DefaultValue("")]
        //public string fullScreenTextColor { get; set; } = "";

        //[global::ProtoBuf.ProtoMember(7)]
        //public Image backgroundImageV2 { get; set; }

        //[global::ProtoBuf.ProtoMember(8)]
        //public PublicAreaCommon publicAreaCommon { get; set; }

        //[global::ProtoBuf.ProtoMember(9)]
        //public Image giftImage { get; set; }

        //[global::ProtoBuf.ProtoMember(11)]
        //public ulong? agreeMsgId { get; set; }

        //[global::ProtoBuf.ProtoMember(12)]
        //public uint? priorityLevel { get; set; }

        //[global::ProtoBuf.ProtoMember(13)]
        //public LandscapeAreaCommon landscapeAreaCommon { get; set; }

        //[global::ProtoBuf.ProtoMember(15)]
        //public ulong? eventTime { get; set; }

        //[global::ProtoBuf.ProtoMember(16)]
        //public bool? sendReview { get; set; }

        //[global::ProtoBuf.ProtoMember(17)]
        //public bool? fromIntercom { get; set; }

        //[global::ProtoBuf.ProtoMember(18)]
        //public bool? intercomHideUserCard { get; set; }

        //[global::ProtoBuf.ProtoMember(20)]
        //[global::System.ComponentModel.DefaultValue("")]
        //public string chatBy { get; set; } = "";

        //[global::ProtoBuf.ProtoMember(21)]
        //public uint? individualChatPriority { get; set; }

        //[global::ProtoBuf.ProtoMember(22)]
        //public Text rtfContent { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LandscapeAreaCommon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool? showHead { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool? showNickname { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool? showFontColor { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"colorValueList")]
        public global::System.Collections.Generic.List<string> colorValueLists { get; set; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(5, Name = @"commentTypeTagsList", IsPacked = true)]
        public global::System.Collections.Generic.List<CommentTypeTag> commentTypeTagsLists { get; set; } = new global::System.Collections.Generic.List<CommentTypeTag>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomUserSeqMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ranksList")]
        public global::System.Collections.Generic.List<RoomUserSeqMessageContributor> ranksLists { get; set; } = new global::System.Collections.Generic.List<RoomUserSeqMessageContributor>();

        [global::ProtoBuf.ProtoMember(3, Name = @"total")]
        public long? Total { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string popStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"seatsList")]
        public global::System.Collections.Generic.List<RoomUserSeqMessageContributor> seatsLists { get; set; } = new global::System.Collections.Generic.List<RoomUserSeqMessageContributor>();

        [global::ProtoBuf.ProtoMember(6, Name = @"popularity")]
        public long? Popularity { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public long? totalUser { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string totalUserStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string totalStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string onlineUserForAnchor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string totalPvForAnchor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue("")]
        public string upRightStatsStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue("")]
        public string upRightStatsStrComplete { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CommonTextMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"scene")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Scene { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateFanTicketMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string roomFanTicketCountText { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public ulong? roomFanTicketCount { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool? forceUpdate { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomUserSeqMessageContributor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"score")]
        public ulong? Score { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"rank")]
        public ulong? Rank { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"delta")]
        public ulong? Delta { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool? isHidden { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string scoreDescription { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string exactlyScore { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong? giftId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong? fanTicketCount { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong? groupCount { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ulong? repeatCount { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ulong? comboCount { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public User toUser { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public uint? repeatEnd { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public TextEffect textEffect { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public ulong? groupId { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public ulong? incomeTaskgifts { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public ulong? roomFanTicketCount { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"priority")]
        public GiftIMPriority Priority { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"gift")]
        public GiftStruct Gift { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        [global::System.ComponentModel.DefaultValue("")]
        public string logId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(17)]
        public ulong? sendType { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public PublicAreaCommon publicAreaCommon { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public Text trayDisplayText { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public ulong? bannedDisplayEffects { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        public bool? displayForSelf { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        [global::System.ComponentModel.DefaultValue("")]
        public string interactGiftInfo { get; set; } = "";

        [global::ProtoBuf.ProtoMember(27)]
        [global::System.ComponentModel.DefaultValue("")]
        public string diyItemInfo { get; set; } = "";

        [global::ProtoBuf.ProtoMember(28, Name = @"minAssetSetList", IsPacked = true)]
        public ulong[] minAssetSetLists { get; set; }

        [global::ProtoBuf.ProtoMember(29)]
        public ulong? totalCount { get; set; }

        [global::ProtoBuf.ProtoMember(30)]
        public uint? clientGiftSource { get; set; }

        [global::ProtoBuf.ProtoMember(32, Name = @"toUserIdsList", IsPacked = true)]
        public ulong[] toUserIdsLists { get; set; }

        [global::ProtoBuf.ProtoMember(33)]
        public ulong? sendTime { get; set; }

        [global::ProtoBuf.ProtoMember(34)]
        public ulong? forceDisplayEffects { get; set; }

        [global::ProtoBuf.ProtoMember(35)]
        [global::System.ComponentModel.DefaultValue("")]
        public string traceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(36)]
        public ulong? effectDisplayTs { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftStruct : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"image")]
        public Image Image { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"describe")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Describe { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"notify")]
        public bool? Notify { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"duration")]
        public ulong? Duration { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"id")]
        public ulong? Id { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool? forLinkmic { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"doodle")]
        public bool? Doodle { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public bool? forFansclub { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"combo")]
        public bool? Combo { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"type")]
        public uint? Type { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public uint? diamondCount { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public bool? isDisplayedOnPanel { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public ulong? primaryEffectId { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public Image giftLabelIcon { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(17, Name = @"region")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Region { get; set; } = "";

        [global::ProtoBuf.ProtoMember(18, Name = @"manual")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Manual { get; set; } = "";

        [global::ProtoBuf.ProtoMember(19)]
        public bool? forCustom { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"icon")]
        public Image Icon { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public uint? actionType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftIMPriority : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"queueSizesList", IsPacked = true)]
        public ulong[] queueSizesLists { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong? selfQueuePriority { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"priority")]
        public ulong? Priority { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextEffect : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"portrait")]
        public TextEffectDetail Portrait { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"landscape")]
        public TextEffectDetail Landscape { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextEffectDetail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"text")]
        public Text Text { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint? textFontSize { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"background")]
        public Image Background { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"start")]
        public uint? Start { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"duration")]
        public uint? Duration { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"x")]
        public uint? X { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"y")]
        public uint? Y { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"width")]
        public uint? Width { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"height")]
        public uint? Height { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public uint? shadowDx { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public uint? shadowDy { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public uint? shadowRadius { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue("")]
        public string shadowColor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.ComponentModel.DefaultValue("")]
        public string strokeColor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15)]
        public uint? strokeWidth { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemberMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong? memberCount { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"operator")]
        public User Operator { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool? isSetToAdmin { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool? isTopUser { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ulong? rankScore { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public ulong? topUserNo { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public ulong? enterType { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"action")]
        public ulong? Action { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string actionDescription { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12)]
        public ulong? userId { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public EffectConfig effectConfig { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.ComponentModel.DefaultValue("")]
        public string popStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15)]
        public EffectConfig enterEffectConfig { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public Image backgroundImage { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public Image backgroundImageV2 { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public Text anchorDisplayText { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public PublicAreaCommon publicAreaCommon { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public ulong? userEnterTipType { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public ulong? anchorEnterTipType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PublicAreaCommon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Image userLabel { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong? userConsumeInRoom { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong? userSendGiftCntInRoom { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EffectConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public ulong? Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"icon")]
        public Image Icon { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong? avatarPos { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"text")]
        public Text Text { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public Image textIcon { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint? stayTime { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ulong? animAssetId { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"badge")]
        public Image Badge { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"flexSettingArrayList", IsPacked = true)]
        public ulong[] flexSettingArrayLists { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public Image textIconOverlay { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public Image animatedBadge { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public bool? hasSweepLight { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"textFlexSettingArrayList", IsPacked = true)]
        public ulong[] textFlexSettingArrayLists { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public ulong? centerAnimAssetId { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public Image dynamicImage { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"extraMap")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> extraMaps { get; set; } = new global::System.Collections.Generic.Dictionary<string, string>();

        [global::ProtoBuf.ProtoMember(17)]
        public ulong? mp4AnimAssetId { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"priority")]
        public ulong? Priority { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public ulong? maxWaitTime { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        [global::System.ComponentModel.DefaultValue("")]
        public string dressId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(21, Name = @"alignment")]
        public ulong? Alignment { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public ulong? alignmentOffset { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Text : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string defaultPatter { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public TextFormat defaultFormat { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"piecesList")]
        public global::System.Collections.Generic.List<TextPiece> piecesLists { get; set; } = new global::System.Collections.Generic.List<TextPiece>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextPiece : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public bool? Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"format")]
        public TextFormat Format { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string stringValue { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public TextPieceUser userValue { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public TextPieceGift giftValue { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public TextPieceHeart heartValue { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public TextPiecePatternRef patternRefValue { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public TextPieceImage imageValue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextPieceImage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"image")]
        public Image Image { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float? scalingRate { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextPiecePatternRef : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string defaultPattern { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextPieceHeart : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"color")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Color { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextPieceGift : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong? giftId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PatternRef nameRef { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PatternRef : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string defaultPattern { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextPieceUser : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool? withColon { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextFormat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"color")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Color { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"bold")]
        public bool? Bold { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"italic")]
        public bool? Italic { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"weight")]
        public uint? Weight { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint? italicAngle { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint? fontSize { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool? useHeighLightColor { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public bool? useRemoteClor { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count")]
        public ulong? Count { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"total")]
        public ulong? Total { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"color")]
        public ulong? Color { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"icon")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Icon { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public DoubleLikeDetail doubleLikeDetail { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public DisplayControlInfo displayControlInfo { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public ulong? linkmicGuestUid { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"scene")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Scene { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11)]
        public PicoDisplayInfo picoDisplayInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong? shareType { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"action")]
        public ulong? Action { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string shareTarget { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public ulong? followCount { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public PublicAreaCommon publicAreaCommon { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PicoDisplayInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong? comboSumCount { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"emoji")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Emoji { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public Image emojiIcon { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string emojiText { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DoubleLikeDetail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool? doubleFlag { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint? seqId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint? renewalsNum { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint? triggersNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DisplayControlInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool? showText { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool? showIcons { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EpisodeChatMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Message Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public bool? visibleToSende { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public Image giftImage { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public ulong? agreeMsgId { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"colorValueList")]
        public global::System.Collections.Generic.List<string> colorValueLists { get; set; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchAgainstScoreMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"against")]
        public Against Against { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint? matchStatus { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint? displayStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Against : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string leftName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public Image leftLogo { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string leftGoal { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string rightName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public Image rightLogo { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string rightGoal { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"timestamp")]
        public ulong? Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"version")]
        public ulong? Version { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public ulong? leftTeamId { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public ulong? rightTeamId { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public ulong? diffSei2absSecond { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public uint? finalGoalStage { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public uint? currentGoalStage { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public uint? leftScoreAddition { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public uint? rightScoreAddition { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public ulong? leftGoalInt { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public ulong? rightGoalInt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Common : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"method")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Method { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public ulong? msgId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong? roomId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong? createTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"monitor")]
        public uint? Monitor { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool? isShowMsg { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"describe")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Describe { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9)]
        public ulong? foldType { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public ulong? anchorFoldType { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public ulong? priorityScore { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue("")]
        public string logId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue("")]
        public string msgProcessFilterK { get; set; } = "";

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.ComponentModel.DefaultValue("")]
        public string msgProcessFilterV { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public ulong? anchorFoldTypeV2 { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public ulong? processAtSeiTimeMs { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public ulong? randomDispatchMs { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public bool? isDispatch { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public ulong? channelId { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public ulong? diffSei2absSecond { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public ulong? anchorFoldDuration { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class User : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        //[global::ProtoBuf.ProtoMember(1, Name = @"id")]
        //public ulong? Id { get; set; }

        //[global::ProtoBuf.ProtoMember(2)]
        //public ulong? shortId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickName { get; set; } = "";

        //[global::ProtoBuf.ProtoMember(4, Name = @"gender")]
        //public uint? Gender { get; set; }

        //[global::ProtoBuf.ProtoMember(5)]
        //[global::System.ComponentModel.DefaultValue("")]
        //public string Signature { get; set; } = "";

        //[global::ProtoBuf.ProtoMember(6)]
        //public uint? Level { get; set; }

        //[global::ProtoBuf.ProtoMember(7)]
        //public ulong? Birthday { get; set; }

        //[global::ProtoBuf.ProtoMember(8)]
        //[global::System.ComponentModel.DefaultValue("")]
        //public string Telephone { get; set; } = "";

        //[global::ProtoBuf.ProtoMember(9)]
        //public Image AvatarThumb { get; set; }

        //[global::ProtoBuf.ProtoMember(10)]
        //public Image AvatarMedium { get; set; }

        //[global::ProtoBuf.ProtoMember(11)]
        //public Image AvatarLarge { get; set; }

        //[global::ProtoBuf.ProtoMember(12)]
        //public bool? Verified { get; set; }

        //[global::ProtoBuf.ProtoMember(13)]
        //public uint? Experience { get; set; }

        //[global::ProtoBuf.ProtoMember(14, Name = @"city")]
        //[global::System.ComponentModel.DefaultValue("")]
        //public string City { get; set; } = "";

        //[global::ProtoBuf.ProtoMember(15)]
        //public int? Status { get; set; }

        //[global::ProtoBuf.ProtoMember(16)]
        //public ulong? CreateTime { get; set; }

        //[global::ProtoBuf.ProtoMember(17)]
        //public ulong? ModifyTime { get; set; }

        //[global::ProtoBuf.ProtoMember(18)]
        //public uint? Secret { get; set; }

        //[global::ProtoBuf.ProtoMember(19)]
        //[global::System.ComponentModel.DefaultValue("")]
        //public string ShareQrcodeUri { get; set; } = "";

        //[global::ProtoBuf.ProtoMember(20)]
        //public uint? IncomeSharePercent { get; set; }

        //[global::ProtoBuf.ProtoMember(21, Name = @"BadgeImageList")]
        //public global::System.Collections.Generic.List<Image> BadgeImageLists { get; set; } = new global::System.Collections.Generic.List<Image>();

        //[global::ProtoBuf.ProtoMember(22)]
        //public FollowInfo FollowInfo { get; set; }

        //[global::ProtoBuf.ProtoMember(26)]
        //[global::System.ComponentModel.DefaultValue("")]
        //public string SpecialId { get; set; } = "";

        //[global::ProtoBuf.ProtoMember(27)]
        //public Image AvatarBorder { get; set; }

        //[global::ProtoBuf.ProtoMember(28)]
        //public Image Medal { get; set; }

        //[global::ProtoBuf.ProtoMember(29, Name = @"RealTimeIconsList")]
        //public global::System.Collections.Generic.List<Image> RealTimeIconsLists { get; set; } = new global::System.Collections.Generic.List<Image>();

        //[global::ProtoBuf.ProtoMember(38)]
        //[global::System.ComponentModel.DefaultValue("")]
        //public string displayId { get; set; } = "";

        //[global::ProtoBuf.ProtoMember(46)]
        //[global::System.ComponentModel.DefaultValue("")]
        //public string secUid { get; set; } = "";

        //[global::ProtoBuf.ProtoMember(1022)]
        //public ulong? fanTicketCount { get; set; }

        //[global::ProtoBuf.ProtoMember(1028)]
        //[global::System.ComponentModel.DefaultValue("")]
        //public string idStr { get; set; } = "";

        //[global::ProtoBuf.ProtoMember(1045)]
        //public uint? ageRange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FollowInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong? followingCount { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong? followerCount { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong? followStatus { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong? pushStatus { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string remarkName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string followerCountStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string followingCountStr { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Image : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"urlListList")]
        public global::System.Collections.Generic.List<string> urlListLists { get; set; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"height")]
        public ulong? Height { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"width")]
        public ulong? Width { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avgColor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public uint? imageType { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string openWebUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"content")]
        public ImageContent Content { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public bool? isAnimated { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public NinePatchSetting FlexSettingList { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public NinePatchSetting TextSettingList { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NinePatchSetting : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"settingListList")]
        public global::System.Collections.Generic.List<string> settingListLists { get; set; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ImageContent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string fontColor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        public ulong? Level { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string alternativeText { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PushFrame : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong? seqId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong? logId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"service")]
        public ulong? Service { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"method")]
        public ulong? Method { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"headersList")]
        public global::System.Collections.Generic.List<HeadersList> headersLists { get; set; } = new global::System.Collections.Generic.List<HeadersList>();

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string payloadEncoding { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string payloadType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"payload")]
        public byte[] Payload { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"kk")]
    public partial class Kk : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(14, Name = @"k")]
        public uint? K { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendMessageBody : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string conversationId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public uint? conversationType { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong? conversationShortId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"ext")]
        public global::System.Collections.Generic.List<ExtList> Exts { get; set; } = new global::System.Collections.Generic.List<ExtList>();

        [global::ProtoBuf.ProtoMember(6)]
        public uint? messageType { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"ticket")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ticket { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clientMessageId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExtList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Rsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"a")]
        public int? A { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"b")]
        public int? B { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"c")]
        public int? C { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"d")]
        [global::System.ComponentModel.DefaultValue("")]
        public string D { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"e")]
        public int? E { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public F f { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"g")]
        [global::System.ComponentModel.DefaultValue("")]
        public string G { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"h")]
        public ulong? H { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"i")]
        public ulong? I { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"j")]
        public ulong? J { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class F : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"q1")]
            public ulong? Q1 { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"q3")]
            public ulong? Q3 { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"q4")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Q4 { get; set; } = "";

            [global::ProtoBuf.ProtoMember(5, Name = @"q5")]
            public ulong? Q5 { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PreMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cmd")]
        public uint? Cmd { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint? sequenceId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string sdkVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"refer")]
        public uint? Refer { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint? inboxType { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildNumber { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8)]
        public SendMessageBody sendMessageBody { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"aa")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Aa { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string devicePlatform { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, Name = @"headers")]
        public global::System.Collections.Generic.List<HeadersList> Headers { get; set; } = new global::System.Collections.Generic.List<HeadersList>();

        [global::ProtoBuf.ProtoMember(18)]
        public uint? authType { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"biz")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Biz { get; set; } = "";

        [global::ProtoBuf.ProtoMember(22, Name = @"access")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Access { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeadersList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CommentTypeTag
    {
        [global::ProtoBuf.ProtoEnum(Name = @"COMMENTTYPETAGUNKNOWN")]
        Commenttypetagunknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"COMMENTTYPETAGSTAR")]
        Commenttypetagstar = 1,
    }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
